name = "academia-addison"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "."

# Pages usa [env.production.vars], NO [vars] suelto
[env.production.vars]
NEXT_PUBLIC_LIVEKIT_URL = "wss://academia-addison.duckdns.org"
LIVEKIT_URL = "wss://academia-addison.duckdns.org"
LIVEKIT_API_KEY = "devkey_addison"