name = "academia-addison"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./"

[vars]
ORACLE_UPLOAD_URL = "https://TU-ORACLE.com/upload"
LIVEKIT_URL = "wss://academia-addison.duckdns.org"
